### ISSUE TITLE
ct_tmp COOKIE ErrorException

### ISSUE THREAD

**Issue by filiviu** [CleanTalk/php-antispam#13]
Hi,
We had this ErrorException for a dodgy registration request. I suspect it was a bot or something similar.

`exception 'ErrorException' with message 'Undefined index: COOKIE' in cleantalk.class.php:748`

Can you please cover the situation when there is no "Cookie", "cookie" or "COOKIE" index on ct_tmp ?

Thanks!

**Comment by safronik** [comment]
Hello,

Yes we could. We'll fix that in the nearest few hours. Thank you for the feedback.

**Comment by safronik** [comment]
The issue have been fixed. Let us know if you have questions.
