### ISSUE TITLE
Сделайте компонент для ICMS 2

### ISSUE THREAD

**Issue by nomad48** [CleanTalk/php-antispam#15]
Добрый вечер, сделайте пожалуйста компонент Анти_СПАМ для [ICMS 2](https://github.com/instantsoft/icms2).  Искал у Вас готовое решение, но именно этой CMS не нашёл. Спасибо.

**Comment by Serge00** [comment]
Здравствуйте.

Да, Вы правы, готового решения для ICMS 2 у нас нет.

В таких случаях мы предлагаем для использования наши API методы. Подробности по ним можно найти на нашей странице помощи здесь:
https://cleantalk.org/help/api-main

Спасибо.

**Comment by nomad48** [comment]
@Serge00 мне было бы проще если был бы компонент и устанавливался он из админки сайта, как для WordPress. Было бы решение, я бы сразу продлил годовую подписку, а так...
Почему Вы не хотите сделать компонент? Есть вся [документация](http://docs.instantcms.ru/dev/start) и она в открытом доступе по ICMS 2

**Comment by Serge00** [comment]
Планов по написанию антиспам компонента для ICMS 2 у нас нет.

Дополнительно мы бы хотели упомянуть, что в течение 2 недель мы выпустим инсталятор от CleanTalk для тех CMS, для которых модулей нет.

Спасибо.

**Comment by nomad48** [comment]
@Serge00 спасибо за ответ, буду ждать результат.

**Comment by Serge00** [comment]
Всегда пожалуйста.

Вы можете следить за новостями компании CleanTalk здесь:
   1. Форум — https://community.cleantalk.org/viewforum.php?f=42
   2. Twitter — https://twitter.com/cleantalk_en
   3. Ваша Панель управления CleanTalk — https://cleantalk.org/my/

Всего доброго.

**Comment by nomad48** [comment]
Да, я везде слежу.

**Comment by nomad48** [comment]
Обратите внимание пожалуйста, на этот [компонент](http://www.instantcms.ru/blogs/instantsoft/generator-komponentov.html), я думаю Вас это заинтересует.
