### ISSUE TITLE
CURL ошибка: "SSL: certificate subject name

### ISSUE THREAD

**Issue by Alexufo** [CleanTalk/php-antispam#16]
Регулярно сыпится на почту сообщения с сервера
```
CURL ошибка: "SSL: certificate subject name '*.cleantalk.org' does not
match target host name '88.198.153.60'" или выключена настройка
allow_url_fopen в php.ini.
```

**Comment by safronik** [comment]
Hello, we gonna fix it 1-2 days.

**Comment by safronik** [comment]
Hello,

Sorry for late response. We have fixed the problem. You could download new version from here: [https://github.com/CleanTalk/php-antispam/archive/master.zip](url)

Please, inform us if the problem still persists.
