### ISSUE TITLE
apache_request_headers doesn't exists on PHP-FPM

### ISSUE THREAD

**Issue by vahidov** [CleanTalk/php-antispam#19]
Subj.
In the previous version (without classes), you controlled function_exists and applied custom functions.

But in the current version, the cleantalk-php-patch file doesn't include and doesn't work.

As a solution, I recommend using the php getallheaders () function, an analogue of apache_request_headers, but operating in fpm mode.

P.S. tested on php 7.2.6 FPM/FastCGI

**Comment by davydovct** [comment]
Hello,

I've added php-patch to composer. Please, update.
https://github.com/CleanTalk/php-antispam/commit/9830fe5580740d54e5b781be3bfa2404a87e336c#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R10

**Comment by shagimuratov** [comment]
Хорошо.

**Comment by vahidov** [comment]
@davydovct 
You need to bump new release too for correct composer update
