### ISSUE TITLE
PHP version requirements

### ISSUE THREAD

**Issue by peter279k** [CleanTalk/php-antispam#21]
In `README`, the PHP version requirements are `php-4.3+`.

At this moment, the official PHP team still support the PHP versions are `php-5.6`, `php-7.0`, `php-7.1`, `php-7.2` and `php-7.3`.

The `php-5.6` and `php-7.0` will be end of life at recent time.

IMHO, we should consider let this PHP package require `php-7.1` version at least.

**Comment by davydovct** [comment]
Hello,

Thanks, this requirement was from the previous library version, so it shouldn't compatibly with PHP 4.3 right now. However, a lot of websites/frameworks are still using an old 5.6 version so we have to do support it, and we can't set the requirement for PHP 7.1 at this time. 

Anyway, thanks for your feedback!

**Comment by peter279k** [comment]
Hi @davydovct, thanks for your reply.

That's fine to support `php-5.6` because of explanation.
