### ISSUE TITLE
Rename namespace from "lib" to be more precise

### ISSUE THREAD

**Issue by tomtomau** [CleanTalk/php-antispam#25]
Currently the namespace for the classes used is `lib` so a consumer of this package will `use lib\Cleantalk;`

Namespaces should be unique across the ecosystem and I don't think that something as generic as `lib` is sufficiently unique to assign to CleanTalk.

I propose that the namespace should be renamed to `Cleantalk`:

```
use Cleantalk\CleanTalk;
```

This will be a breaking change so the major version should be bumped accordingly.

Cheers

**Comment by Glomberg** [comment]
Hello @tomtomau 
Thank you for your attention to the details.
We have changed the namespace and have pushed these changes to the branch. https://github.com/CleanTalk/php-antispam/commit/204fe1ce21f91a7691d7873938cc1036f24b1a43

**Comment by tomtomau** [comment]
I think you may need to change the psr-4 setting in composer.json too?

https://github.com/CleanTalk/php-antispam/blob/master/composer.json#L12

**Comment by Glomberg** [comment]
Yes. Forgot. Thank you. Fixed. https://github.com/CleanTalk/php-antispam/commit/4475e95d2e8fa6bd4f6eb0dd4ccf9b6930bb64aa
