### ISSUE TITLE
Undefined variable: $servers

### ISSUE THREAD

**Issue by rand0mdev** [CleanTalk/php-antispam#26]
Hi,
I was testing my Symfony app to use this library but when i call the`isAllowMessage` function, i get this error:
`Undefined variable: servers`

In fact this variable doesn't exists in the function:
https://github.com/CleanTalk/php-antispam/blob/b951451a73ad89b47f5b318d443a90137b640c08/lib/Cleantalk.php#L446-L470

**Comment by Glomberg** [comment]
Hello,
thank you for the feedback.
The issue was fixed https://github.com/CleanTalk/php-antispam/commit/2515e2839ec1d1fc8c04c0855797eca30f4990a8
