### ISSUE TITLE
Readme 'use' path is wrong

### ISSUE THREAD

**Issue by varna9000** [CleanTalk/php-antispam#29]
I'm using composer for the install. The Readme example which reads 
```
use lib\Cleantalk;
use lib\CleantalkRequest;
```

does't work with composer.

If I use the path from the example.php it works:
```
use Cleantalk\CleantalkRequest;
use Cleantalk\Cleantalk;
```

**Comment by ardavydov** [comment]
Thanks, fixed:
https://github.com/CleanTalk/php-antispam/commit/5f6d0b6383b53132685dbaac84090be2760626bf
