### ISSUE TITLE
Missing includes

### ISSUE THREAD

**Issue by gjedeer** [CleanTalk/php-antispam#34]
Your example code from readme does not work without additionally including:

/cleantalk-php/lib/cleantalk-php-patch.php

and

/cleantalk-php/lib/CleantalkResponse.php

**Comment by alexandergull** [comment]
Hello!

We will check this in a few days.

Thanks.

**Comment by svfcode** [comment]
Thanks for issue about CleantalkResponse class required. Now it fixed.

Please show the problem with cleantalk-php-patch.php. On research, it works fine.
