### ISSUE TITLE
Case-Sensitivity - Namespace (CleanTalk vs Cleantalk)

### ISSUE THREAD

**Issue by ConnectGrid** [CleanTalk/php-antispam#36]
I'm a firm believer in honouring and respecting a name with its proper case, and this project is clearly called "CleanTalk", with a capital "T".

Throughout this codebase, the class namespaces are written "Cleantalk", whereas other references in the project have the name written as "CleanTalk". This is confusing, and also interferes with PSR-4 autoloading. A developer would need to know to always write `Cleantalk` for the namespace for autoloading to work.

I know many developers adhere strictly to `Abcdefgh` case, where only the first letter is uppercased, but I think exceptions should be made for the case of proper names.

The `PSR-4: Autoloading` gives the following example:
`\<NamespaceName>(\<SubNamespaceNames>)*\<ClassName>`

You can clearly see that they have a capital "N" partway through the namespace names.

They also state this:
- Alphabetic characters in the fully qualified class name MAY be any **combination of lower case and upper case**.

I would like to see this library adhere stricktly to "CleanTalk" case throughout the code and documentation. That is the project's name, after all. This consistency removes the confusion about how the namespace must be written just for the autoloader to work.

Thoughts?

**Comment by alexandergull** [comment]
Hello. Thank you. We will check this in a few days.

**Comment by ArtemAnoshin** [comment]
Hello and thank you for waiting.
We decided to refuse making changes to the namespace that is already being used in our current projects, as it requires much work and doesn't bring any practical profit. However, in the future projects we will take into account your suggestions and do our best to use exactly "CleanTalk" in the namespace.
All the best.
