### ISSUE TITLE
CURL error: OpenSSL SSL_read: error

### ISSUE THREAD

**Issue by llegaz** [CleanTalk/php-antispam#39]
I was crumbling on this error

`CURL error: 'OpenSSL SSL_read: error:0A000126:SSL routines::unexpected eof while reading, errno 0' or disabled allow_url_fopen in php.ini`

until I changed in `Cleantalk.php` the line 306 from
```php
curl_setopt($ch, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_0);
```
to 
```php
curl_setopt($ch, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
```

php5.6-fpm
openssl3.0.2
buntu 22.04

**Comment by Glomberg** [comment]
Hi @llegaz 
Thank you for the attention.
We will plan to reject the option `CURLOPT_HTTP_VERSION` altogether.

The next release will waiting about a month.

**Comment by llegaz** [comment]
Good.

**Comment by alexandergull** [comment]
Hello @llegaz 

Version 3.2 has been released. 

https://github.com/CleanTalk/php-antispam/releases/tag/3.2

The cURL option has been removed.
