### ISSUE TITLE
extending Cleantalk: private methods

### ISSUE THREAD

**Issue by drzraf** [CleanTalk/php-antispam#40]
`httpRequest`, ;`createMsg`  and `filterRequest` are **private** instead of **protected** and a class extending `Cleantalk` (to add a `spam_check` / `isSpam()` method, for example) can't make use of these useful methods)

Please change their visibility to ease inheritance, extension and re-usability of this library.

**Comment by Glomberg** [comment]
Hi @drzraf 
Thank you for your attention.
No need `Cleantalk` extending classes to implement such methods as you provide. Just implement these methods in you own class. See [example here](https://github.com/CleanTalk/php-antispam/blob/master/lib/CleantalkAntispam.php#L28), this is is_spam-like method.

**Comment by drzraf** [comment]
Please reopen, I believe you didn't understood the issue at stake:

```php
class CleantalkSpamCheck extends Cleantalk
{
    public $ssl_on = true;
    private $server_timeout = 15;
    private $data;

    public function isSpam(CleantalkRequest $request) {
        $request = $this->filterRequest($request);
        $filtered_request = $this->createMsg('spam_check', $request);
        $this->data = $filtered_request->data;

        return $this->httpRequest($filtered_request);
    }
    protected function httpRequest($msg)
    { ... }
```

I'm fine rewriting `httpRequest` and `sendRequest`, but I **must** be able to override `httpRequest`.
(Otherwise I can't even support batch mode)

**Comment by Glomberg** [comment]
> I must be able to override httpRequest.

Maybe it will be suitable to write a new method? If you want to make an own realization.

```php
class CleantalkSpamCheck extends Cleantalk
{
    public $ssl_on = true;
    private $server_timeout = 15;
    private $data;

    public function isSpam(CleantalkRequest $request) {
        $request = $this->filterRequest($request);
        $filtered_request = $this->createMsg('spam_check', $request);
        $this->data = $filtered_request->data;

        return $this->newHttpRequest($filtered_request);
    }
    protected function newHttpRequest($msg)
    { ... }
}
```

**Comment by drzraf** [comment]
Same regarding `filterRequest` and `createMsg`. What the underlying design? And why OOP if the code is made impossible to reuse?

**Comment by Glomberg** [comment]
We discussed this case with the team and accepted a decision—we do not change common classes for the one custom case. There is no need to extend these core classes.
More details:
How do you implement your requirements? You just used the application incorrectly. This application only handles anti-spam-based API methods - `check_newuser`, `check_message`, and `send_feedback`. Other API methods implementation you are able to implement using Cleantalk API. So, do you want to connect the `spam_check` method? Use this [API documentation](https://cleantalk.org/help/api-spam-check)  (note, this method not be able to be implemented in Cleantalk class, this method calls not anti-spam servers, but api.cleantalk.org).
