### ISSUE TITLE
Check multiple IPs in one request with this API

### ISSUE THREAD

**Issue by 2ge** [CleanTalk/php-antispam#7]
is this possible ?

**Comment by CleanTalk** [comment]
No.

**Comment by CleanTalk** [comment]
But it's allowed here: https://cleantalk.org/help/api-spam-check

**Comment by 2ge** [comment]
Thanks for fast answer. So I will use https://cleantalk.org/help/api-spam-check - I can not find info about some data. My usage is checking only by IP. Questions:
- how many IPs I can pass ? Is this limited, or there is some recommended value ?
- what value you recommend to use as TimeOut for http request?
- what is exactly limits ? I see I can get "Calls limit exceeded." - I dont want to overload your service, so I need to know how many requests per second I can send or some limit...

Thanks!

**Comment by CleanTalk** [comment]
Great questions. We are going to add needed information on the page. I'll inform you here when ready.

**Comment by CleanTalk** [comment]
Hello again!
Have a look at https://cleantalk.org/help/api-spam-check - information is added.

**Comment by 2ge** [comment]
Hi,

thanks for updating this info. You got small typo "Current calls limit is 3 per 30 sesonds."
Also this call limit seems quite small (and what are limits for this php-antispam lib?), it is possible to raise the limits if needed ?

**Comment by CleanTalk** [comment]
Thanks, typo is fixed.

spam_check method isn't our main product. So it has such limit. But it can be raised if **really** needed.

php-antispam library has no limits at all because it's our main product. See details of its methods:
https://cleantalk.org/help/api-check-newuser
https://cleantalk.org/help/api-check-message
https://cleantalk.org/help/api-send-feedback

**Comment by 2ge** [comment]
I think it should be OK to raise limit at least for 10 queries per 30 seconds. I use only this one, because I need to compare IP address for suspicious behaviour (no registration/no comment but download action) and then decide if show CAPTCHA.

If there would be some export with all IPs included in spam_check that would be even better, it is possible to make export for paying users?

**Comment by CleanTalk** [comment]
We'll increase limit (for this metod only). I'll write here when done.
Sure, to obtain our spam networks it's better to use this: https://wiki.cleantalk.org/doku.php?id=api_spam_active_networks

**Comment by 2ge** [comment]
thanks. so it means around 8316 IPs address are active (marked as spammy) right now. It is all same IPs I will get using https://cleantalk.org/help/api-spam-check (3 black points in past 45 days), or it is a bit different list ? I thought flagged IPS (appears  = 1) is bigger then  https://wiki.cleantalk.org/doku.php?id=api_spam_active_networks count of IPs, or I am wrong ?

**Comment by CleanTalk** [comment]
You are right. This list is shorter than 3 black points in past 45 days. It's used in our SpamFireWall feature. https://cleantalk.org/help/cleantalk-spam-firewall
But remember that this list includes entire networks, not single IPs only.

**Comment by 2ge** [comment]
Yes, I just find out it is not same list. It is possible to get same list (3 points in past 45 days) ?
Otherwise I have to use https://cleantalk.org/help/api-spam-check to get those IPs. For giving captcha to entire network - I think not so good idea, because if in network is 3 "spammy" IPs, I dont want to show captcha to rest "clean" IPs. For me, not so big problem to use https://cleantalk.org/help/api-spam-check - but of course much more effective if I could get list of "bad" IPs.

Thanks for excellent support

**Comment by CleanTalk** [comment]
Of course we put only networks with really bad reputation. Not AS's but subnets, sure.

**Comment by CleanTalk** [comment]
As for list of 3 points in past 45 days - please write us to welcome@cleantalk.org
Thanks for the issue!

**Comment by 2ge** [comment]
thanks, will do.

**Comment by CleanTalk** [comment]
We've tuned limit for spam_check() calls.
Now it is 100 calls per 60 seconds.
Please check and feel free to write us any comments!
